language: php

php:
- hhvm-nightly
- hhvm
- nightly
- 5.6
- 5.5
- 5.5.9
- 5.4
- 5.3
- 5.3.3

env:
- COVER=1
- COVER=0

matrix:
  # skip all cover-build except for "php: 5.6"
 exclude:
  - env: COVER=1
 include:
  - php: 5.6
    env: COVER=1
 allow_failures:
  # run this coverage build, but allow failure
  - php: 5.6
    env: COVER=1

# validated with: http://lint.travis-ci.org/
# os:          # error: your repository must be feature flagged for the os setting to be used
# - linux
# - osx        # error: in os section: dropping osx, does not support php

before_script:
 - if [[ "$COVER" == 1 ]]; then composer require codeclimate/php-test-reporter --dev; composer install; fi

script:
 - if [[ "$COVER" == 1 ]]; then phpunit --coverage-clover build/logs/clover.xml; else phpunit; fi

after_script:
 - if [[ "$COVER" == 1 ]]; then ./tools/report_coverage.sh; fi
