language: php

php:
- hhvm-nightly
- hhvm
- nightly
- 7.3
- 7.2
- 7.1
- 7
- 5.6
- 5.5
- 5.5.9
- 5.4
- 5.3
- 5.3.3

env:
- COVER=1
- COVER=0

matrix:
  # skip all cover-build except for "php: 7"
 exclude:
  - env: COVER=1
 include:
  - php: 7
    env: COVER=1
 allow_failures:
  # run this coverage build, but allow failure
  - php: 7
    env: COVER=1
  - php: nightly # nightly build can have bugs, that are no failures for Behind
  - php: hhvm-nightly # currently not supported by travis (no nightly bilds on precise)

  # from travis documentation: https://docs.travis-ci.com/user/languages/php#PHP-installation
  # "Note that the OpenSSL extension is disabled on php 5.3.3 because of compilation problems with OpenSSL 1.0."
  - php: 5.3.3

# validated with: http://lint.travis-ci.org/
# os:          # error: your repository must be feature flagged for the os setting to be used
# - linux
# - osx        # error: in os section: dropping osx, does not support php

sudo: false

addons:
    code_climate:
        repo_token: 99a93b7c64a586c9207ad11a8da9a7dbc2811936dc13c11bbe71653e0fcd9f53

install:
 - composer require phpunit/phpunit:^4 --dev;
 - if [[ "$COVER" == 1 ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then composer require codeclimate/php-test-reporter --dev; fi
 - travis_retry composer install --no-interaction --prefer-source

script:
 - if [[ "$COVER" == 1 ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-text; else vendor/bin/phpunit; fi

after_script:
 - if [[ "$COVER" == 1 ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then CODECLIMATE_REPO_TOKEN=99a93b7c64a586c9207ad11a8da9a7dbc2811936dc13c11bbe71653e0fcd9f53 ./vendor/bin/test-reporter; fi

